### ISSUE TITLE
multiple orders in one /orders POST request

### ISSUE THREAD

**Issue by tw-smith** [stapi-spec/stapi-spec#125]
Can we update the orders spec so that we can POST a list of opportunities and therefore task multiple opportunities in one call to `/orders`?

**Comment by vzup42** [comment]
From another perspective, the user might be interested in taking multiple products for the same geometry.

**Comment by tw-smith** [comment]
In the orders discussion group we thought that being able to submit multiple orders would be useful functionality and there are already existing use cases for this.

However, there are complexities with, for example, error handling. Let's say a client submits an order request with 50 orders and the first 20 are created successfully with the provider but the next 30 fail. The client would get back a response with the STAPI "rejected" error code but in reality there would be 20 valid orders created with provider, creating a mismatch. One possible solution could be to create an "OrdersCollection" object to wrap the individual orders with some sort of composite status.

**Comment by matthewhanson** [comment]
We're moving the /orders endpoint to be per product, see #200 .

We may add a top level /orders endpoint which would presume that you can provide multiple products. In other words, we would allow multiple orders if we add an /order endpoint, but we are deferring the decision of that addition right now so I am closing this as OBE
