### ISSUE TITLE
Make product_id an aray?

### ISSUE THREAD

**Issue by m-mohr** [stapi-spec/stapi-spec#155]
For provider agnostic providers like UP42, does it make sense to make product_id an array for opportunities so that you can review multiple products?

**Comment by nic-planet** [comment]
How would this work with different validation rules for the filter?

**Comment by ReddySwathy** [comment]
True, would only work if you keep the payload to accept geometry and acquisition window only. which is what we do at up42.

**Comment by matthewhanson** [comment]
We're adding opportunities to be product specific, see #198 and would have a "cross-product" /opportunities endpoint which, by it's existence would presume that products are an array to this endpoint.   

So I think this issue no longer valid.
