### ISSUE TITLE
Conflicting documentation regarding relation type for links to order status

### ISSUE THREAD

**Issue by jkeifer** [stapi-spec/stapi-spec#197]
The docs seem to conflict on what relation type to use for links to order status. The docs for [GET /orders](https://github.com/stapi-spec/stapi-spec/tree/main/order#get-orders) say

> If the `GET /orders/{orderId}/status` endpoint is implemented, there must be a link to the endpoint using the relation type `status`."

Whereas the docs for [GET /orders/{id}](https://github.com/stapi-spec/stapi-spec/tree/main/order#get-ordersid) say

> If the `GET /orders/{orderId}/status` endpoint is implemented, there must be a link to the endpoint using the relation type `monitor`.

It seems like the relation type should be the same in both cases as an order object returned from either is the same entity, and thus the links shouldn't differ, right?

Reviewing the [IANA list of relation types](https://www.iana.org/assignments/link-relations/link-relations.xhtml) and the associated RFCs for `status` and `monitor` it seems `status` isn't necessarily a good fit as it appears to be intended for links that provide the status of a given service, not a specific entity returned by a service. `monitor` is a bit more opaque given the originating RFC pertains to SIP, but it seems like it might be a better fit for this use-case at the RFC explicitly calls out the use-case of monitoring changes to a resource managed by an HTTP server.

Is the intent to have both of these lines state that the relation type should be `monitor`?

**Comment by matthewhanson** [comment]
Makes sense, `monitor` is it.

**Comment by jkeifer** [comment]
It appears this issue has been addressed by recent changes. Closing.
