### ISSUE TITLE
Why /opportunities instead of /products/{id}/opportunities?

### ISSUE THREAD

**Issue by jkeifer** [stapi-spec/stapi-spec#198]
It seems like, with `/opportunities` taking a single product ID that a url structure like `/products/{id}/opportunities` would be more ergonomic and meaningful. It would also make it such that APIs could better describe the opportunities response model, as that model is effectively product specific.

Perhaps this is not a either/or but a both/and. Maybe it would make sense to have both `/opportunities` and `/products/{id}/opportunities`, which would up being somewhat functionally synonymous with the STAC API endpoints `/search` and `/collections/{id}/items`. Doing this would require #155 to allow cross-product opportunity aggregation via the `/opportunities` endpoint.

It might then be worth following the STAC API example even further and making filtering an additional conformance class or extension, to simplify the implementation required to meet the core conformance class (and allow new filter grammars in the future).

**Comment by matthewhanson** [comment]
Discussed and agreed this makes sense.  

Need PR to update docs and OpenAPI docs

**Comment by alex-mcelroy** [comment]
Putting together a PR now 👍
