### ISSUE TITLE
Might the POST to /orders also be better considered a /products/{id}/order endpoint?

### ISSUE THREAD

**Issue by jkeifer** [stapi-spec/stapi-spec#200]
Similar to #198, that `POST /orders` takes a product ID might also mean this operation could be more ergonomic as `POST /products/{id}/order`. Doing this could allow better API documentation by allowing specific order request models per product type.

With this endpoint model the spec would also need to support products that cannot be ordered directly: I'm thinking here of a derived product of some type where the order would be to task an collect with an order parameter indicating that the derived product should be generated from the collected image.

**Comment by m-mohr** [comment]
Can orders span multiple products?

**Comment by matthewhanson** [comment]
Having per product order endpoint improves the ability to validate product specific orders using the product definition constraints. 

Decided to add per product order endpoints.

If we want to allow orders to span multiple products we would add a top-level /order endpoint that would allow a list of products, but that is another issue/PR if we decide we want that.

**Comment by jkeifer** [comment]
Closed by #215
