### ISSUE TITLE
Is opportunity the right term?

### ISSUE THREAD

**Issue by jkeifer** [stapi-spec/stapi-spec#202]
I've been struggling when trying to discuss the spec with others. It seems like generally people have a rather good understanding of an opportunity as a very specific section of the path of a given orbit that allows for the collection of a scene of a given place at a given time.

However, as I understand STAPI to allow, that definition may or may not reflect what actually gets returned from the opportunities endpoint, depending on the product in question. For example, a vendor might decide to sell a "collection window" or other time-based SLA-like product during which they might be able to produce a collect of that product. Said another way, a vendor might not sell a specific "opportunity", just that they can produce the item within a given turn-around time. They might provide shorter and longer timelines for more or less money, and these might be the "opportunities objects" returned from the opportunities endpoint.

In such a "collection window" case, it is as if an "opportunity object" returned from the API actually represents multiple collection opportunities rolled up/summarized together, of which one will be tasked and collected. But this is where the terminology makes it so hard to discuss: what is one referring to in this case when they use the word "opportunity"? That specific section of a given orbit, or the summarized "opportunity object" that an end-user would see?

So, to get to the point:

* Is my understand of STAPI correct in that opportunities should allow a vendor to express whatever object it is they want to sell to an end user--a specific opportunity or a summarization of opportunities--that ends up mapping to one or more STAC items?
* If so, is "opportunity" really the most appropriate word here, or can we pick something that provides a bit more disambiguation between what is ordered and what is tasked?
* If yes to this as well, then can we pick two sub-types of whatever that term is, where one means that thing maps to a single specific opportunity to be tasked, and another is a composite of multiple opportunities?
  * Should we disambiguate further between those which take multiple collects to fulfill (large areas) and those that will be fulfilled by one of a set of possible collects?

**Comment by jkeifer** [comment]
May be related to #141.

**Comment by matthewhanson** [comment]
It's a good point, but we decided to not change the name now, just need more documentation and examples of products, see #214
