### ISSUE TITLE
Why /products instead of /collections?

### ISSUE THREAD

**Issue by m-mohr** [stapi-spec/stapi-spec#91]
For me as a STAC-aware user it is not clear why a separate endpoint like /products is needed. It looks like an extended version of /collections, so couldn't these two endpoints be merged?

**Comment by matthewhanson** [comment]
1. I think a product is a STAC Collection, but we did talk about this last time and decided not, perhaps @greyskyy remembers why.

2. Constraints are on the actual data collect, whereas parameters are options on the deliver IIRC.  I'm not sure they need to be separated.

3. What would be the advantage of having constraints in different endpoints?

4. Constraints are similar to summaries in STAC Collections, and could be a RangeObject or JSONSchemaObject

5. The payloads /order and /opportunities I think should be the same.

**Comment by m-mohr** [comment]
Maybe we just keep the response body being a STAC Collection subset where we ensure it doesn't conflict if you want the STAC Collection properties. But this means we need to change the endpoint name to /collections.

**Comment by greyskyy** [comment]
Testing my memory... but I believe we were talking about whether a
"product" is something you can order or something already collected.

We wanted a way to expose the set of "things you can order" to include
various constraints, etc, to clients. This is different than a STAC
collection, which was expressing things which have been collected.

Think about a SAR provider wanting to expose some SAR single-collect
products, and also some multi-collect products (e.g. change detection). A
client would query the API to see what is available to order, and
understand the constraints they can specify.

**Comment by matthewhanson** [comment]
It does appear that a Product is just a STAC Collection (with a`conformsTo`). 

However, we came up with a few reasons to not change the term from Product to Collection:

- Using the same term in two different APIs that will often be used together with each other would be confusing and require disambiguation every time "Collection" is referred to.
- Not everything that gets delivered for a Product order may be a STAC Item (it may be a vector location, a report, or something else).  Internally to the data provider there's probably STAC Items but these may not be what is delivered to the user
- How implementors group individual items into Collections is an internal detail detached from Products
- If Items are delivered as a result of a tasking order they are delivered as a list of as Items which the user may organize into Collections how they see fit, which may be multiple Collections - unrelated to how the provider organizes their Catalog and without a 1:1 relationship with the Products.
