### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by m-mohr** [stapi-spec/stapi-spec#94]
When talking to people at conferences, the name was a bit confusing.
Asking people about STAT, their response was often:
- Ah, yes, I know STAC
- Is this about statistics?

Even when talking to people that know STAT, you often had to clarify whether you talk about STAC or STAT.

Funnily, the A for Asset funnily is not used in any of the specs, there's also no asset field as in STAC.

Feel free to close this, just wanted to quickly report about the experiences. But maybe there's a better alternative?

**Comment by CloudNiner** [comment]
This feedback is awesome! To add a bit of discussion/context...

> Is this about statistics?

Heh -- definitely something to consider. Confusion across domains is frustrating.

> Even when talking to people that know STAT, you often had to clarify whether you talk about STAC or STAT.

Also very interesting, any more details on what the confusion was?

> A for Asset funnily is not used in any of the spec

When we were brainstorming, we mostly focused on the "input" side, or how do I provide inputs to this specification. As far as I recall, the "Asset" (or output) part was temporarily handwaved away. Looking at the proposed spec again, we have Product and its up to Providers to implement the details of those, so maybe Asset isn't a thing anymore for this spec and is in fact a source for confusion? Maybe in practice most Providers would return results as STAC Assets?

**Comment by m-mohr** [comment]
> > Even when talking to people that know STAT, you often had to clarify whether you talk about STAC or STAT.
> 
> Also very interesting, any more details on what the confusion was?

It was in a noisy environment and then people tend to understand words they know (like STAC) instead of something they don't know, I guess. And of course it sounds similar so your brain tries to connect the bits and pieces... :-)

**Comment by jsignell** [comment]
Yeah I agree that it is too similar to STAC. The main concepts in this spec are "Opportunities" "Orders" and "Products" so both "Asset" and "Tasking" aren't really words that we use. Also unlike STAC this spec seems entirely about satellites so "Spatial Temporal" might even be too broad.

That leads me to do some acronym work...there are a lot of options: 

 - STOP (Spatial Temporal Order Products)
 - POST (Product Ordering - Spatial Temporal)
 - STOT (Spatial Temportal Opportunity Tasking)
 - STO (Satellite Tasking Opportunities)
 - OSP (Ordering Satellite Products)
 - OOPS (Opportunities for Ordering Products from Satellites)

**Comment by m-mohr** [comment]
STAPI - Satellite Tasking API :-)

**Comment by PowerChell** [comment]
Hi all,

This topic is on my mind too often. Was happy to find this issue! Here are some more options/ideas to keep the wheels turning (that I got from ChatGPT 🤪): 

- SOPA (Satellite Opportunity and Product API)
- SAPO (Satellite Product and Opportunity)
     - logo could be a frog because "sapo" is "toad" in Spanish 🐸
- OPSA (Opportunity-based Product Service API)
- FUTURES (Future-oriented Unified Tasking and Retrieval for Earth Sensing) 
- FORD (Future Order and Retrieval Data)
- JOT (JSON-based Ordering and Tracking/Tasking)

**Comment by jedsundwall** [comment]
+1 for SAPO or JOT.

**Comment by mapanauta** [comment]
Now also this topic is stuck in my head :) 
I think we need to not use ST at the beginning of the name to make a strong differentiation, I like to think about Future ordering as a key part of the name, so here are some options below ;) 
- [ ] FuTAPI (Future Tasking API)
- [ ] FuTO (Future Tasking Opportunities)

I like SAPO too because of the frog meaning in Spanish :P

**Comment by captaincoordinates** [comment]
Given today's discussion on terminology and "order" vs "task" vs "capture" etc. we should avoid using "tasking" in the specification's name. There was general agreement that "task" describes a lower-level activity managed by the provider. Although users may be aware of tasks they do not manage tasks via the API. Users manage orders via the API.

**Comment by m-mohr** [comment]
It could even be used for archive orders...

**Comment by m-mohr** [comment]
FORA - Future Order and Retrieval API

**Comment by m-mohr** [comment]
Needs a PR and repo rename, so reopened.
